# Generated by Django 4.0.3 on 2022-05-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creationUser', models.CharField(blank=True, max_length=100, null=True)),
                ('creationTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastUpdatedUser', models.CharField(blank=True, max_length=100, null=True)),
                ('lastUpdateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('parameter', models.FileField(upload_to='uploads/files')),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creationUser', models.CharField(blank=True, max_length=100, null=True)),
                ('creationTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastUpdatedUser', models.CharField(blank=True, max_length=100, null=True)),
                ('lastUpdateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('parameter', models.FileField(upload_to='uploads/datamodels')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creationUser', models.CharField(blank=True, max_length=100, null=True)),
                ('creationTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastUpdatedUser', models.CharField(blank=True, max_length=100, null=True)),
                ('lastUpdateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('parameter', models.FileField(upload_to='uploads/datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Explorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creationUser', models.CharField(blank=True, max_length=100, null=True)),
                ('creationTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastUpdatedUser', models.CharField(blank=True, max_length=100, null=True)),
                ('lastUpdateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('parameter', models.FileField(upload_to='uploads/explorer')),
            ],
        ),
    ]
