# Generated by Django 4.0.3 on 2022-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crishApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='parameter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files'),
        ),
    ]
