# Generated by Django 4.0.3 on 2022-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crishApp', '0002_alter_databaseconnection_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='parameter',
            field=models.FileField(blank=True, default='nothing', null=True, upload_to='uploads/files'),
        ),
    ]
