# Generated by Django 4.0.3 on 2022-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crishApp', '0005_alter_databaseconnection_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='sql_file',
            field=models.FileField(blank=True, null=True, upload_to='upload/sql_file'),
        ),
    ]
