# Generated by Django 4.0.3 on 2022-06-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crishApp', '0006_datasource_sql_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='data_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crishApp.datamodel'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='sql_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sql_file'),
        ),
    ]
