# Generated by Django 4.0.3 on 2022-06-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crishApp', '0008_remove_datasource_data_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='parameter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/dbconnection'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='parameter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/datasource'),
        ),
        migrations.AlterField(
            model_name='explorer',
            name='parameter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/explorer'),
        ),
    ]
