# Generated by Django 4.0.3 on 2022-07-06 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crishApp', '0010_alter_datamodel_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='creationUser',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
