# Generated by Django 4.0.3 on 2022-07-07 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crishApp', '0011_alter_databaseconnection_creationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='creationUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
