# Generated by Django 4.0.3 on 2022-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crishApp', '0014_remove_datasource_sql_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
