# Generated by Django 4.0.3 on 2022-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crishApp', '0015_alter_databaseconnection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='explorer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
